FORMAT: 1A
HOST: cosmos.stake.capital/api

# Cosmos API Stake Capital

API allowing clients to view Cosmos' state and retrieve data from the network.

# GET /status

Get information on the latest block.

From Tendermint RPC endpoint: block

+ Response 200 (application/json)

        {
          "latest_block_hash": "C3A6C2B4298D6A81A55132AA78AF1D159EE1D276052855B30D77B41837FD24CE",
          "latest_app_hash": "02E672666712B0B234A4F144F04F52A5E4A5C56FC248A54344084279121D7EE4",
          "latest_block_height": "224796",
          "latest_block_time": "2019-01-22T15:02:25.142458104Z"
        }

# GET /setup

Get network information.

From Tendermint RPC endpoint net_info

+ Response 200 (application/json)

        {
          "network": "game_of_stakes_3",
          "version": "0.27.3"
        }

# GET /chain_size

Get the size of the blockchain in Kbytes. 

This info will be pushed from the node directly.

+ Response 200 (application/json)

        {
          "chain_size": "256"
        }

# GET /yearly_return

Extends the block reward to a yearly compound return e.g. profits are reinvested.

This info will be pushed from the node directly.

+ Response 200 (application/json)

        {
          "y_return": "10"
        }

# GET /average_reward

Get the average reward per block (in %) including both inflation and transaction fees, based on the last 30 days. 

This info will be pushed from the node directly.

+ Response 200 (application/json)

        {
          "av_reward": "2"
        }